name: Rust Tests

on:
  pull_request:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          profile: minimal
          override: true

      - name: Run cargo test
        run: cargo test
        working-directory: ./rusty_hero_quest

      - name: Capture test output
        run: cargo test -- --nocapture > test-results.txt || true
        working-directory: ./rusty_hero_quest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.txt

  check-tests:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: .

      - name: Check for test failures
        id: check_failures
        run: |
          if grep -q 'test result: FAILED.' test-results.txt; then
            echo "There are test failures."
            exit 1
          else
            echo "All tests passed."
          fi
