name: Rust Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Run cargo test
        run: cd /home/runner/work/rusty_quest/rusty_quest/rusty_hero_quest; cargo test

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/debug/test-results.xml

          
  check-tests:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: ./test-results
  
      - name: Check for test failures
        id: check_failures
        run: |
          if grep -q 'FAILED' ./test-results/test-results.xml; then
            echo "There are test failures."
            echo "failure=true" >> $GITHUB_ENV
          else
            echo "All tests passed."
          fi
  
      - name: Fail if tests fail
        if: env.failure == 'true'
        run: exit 1
